name: Static Site Auto Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Clean subdomain folder before deployment
      - name: Clean Subdomain Folder
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          key: ${{ secrets.CPANEL_SSH_PRIVATE_KEY }}
          port: ${{ secrets.CPANEL_PORT }}
          script: |
            rm -rf /home/sksdeve1/contact.sksdevelopers.lk/*
            mkdir -p /home/sksdeve1/contact.sksdevelopers.lk

      # 3️⃣ Upload project files to subdomain folder (exclude .git)
      - name: Deploy Static Files to Subdomain
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          key: ${{ secrets.CPANEL_SSH_PRIVATE_KEY }}
          port: ${{ secrets.CPANEL_PORT }}
          source: "."
          target: "/home/sksdeve1/contact.sksdevelopers.lk"
          strip_components: 0
          exclude: |
            .git/
            .github/
            node_modules/

      # 4️⃣ Set proper file permissions
      - name: Set File Permissions
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          key: ${{ secrets.CPANEL_SSH_PRIVATE_KEY }}
          port: ${{ secrets.CPANEL_PORT }}
          script: |
            cd /home/sksdeve1/contact.sksdevelopers.lk
            find . -type f -exec chmod 644 {} \;
            find . -type d -exec chmod 755 {} \;

      # 5️⃣ Health check - Verify deployment
      - name: Verify Deployment
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          key: ${{ secrets.CPANEL_SSH_PRIVATE_KEY }}
          port: ${{ secrets.CPANEL_PORT }}
          script: |
            cd /home/sksdeve1/contact.sksdevelopers.lk
            if [ ! -f "index.html" ]; then
              echo "Error: index.html not found!"
              exit 1
            fi
            echo "Deployment verified successfully!"
            echo "Files deployed:"
            ls -lh